export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SET_APPEND_RESULTS = 'SET_APPEND_RESULTS';
export const ADD_RESULT = 'ADD_RESULT';
export const ADD_VARIABLE = 'ADD_VARIABLE';
export const ADD_RESULTS = 'ADD_RESULTS';
export const TOGGLE_VARIABLES = 'TOGGLE_VARIABLES';
export const TOGGLE_VARIABLE = 'TOGGLE_VARIABLE';
export const TOGGLE_COMPARE = 'TOGGLE_COMPARE';
