export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const TOGGLE_APPEND_RESULTS = 'TOGGLE_APPEND_RESULTS';
export const APPEND_RESULT = 'APPEND_RESULT';
export const APPEND_RESULTS = 'APPEND_RESULTS';